name: Release

on:
  push:
    tags:
      - 'v*'  # Runs when a tag like v1.0.0 is pushed

permissions:
  contents: write  # Grants write access to create releases

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build JAR file
        run: ./gradlew build

      - name: Upload JAR to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: app/build/libs/app.jar
          token: ${{ secrets.GITHUB_TOKEN }}  # Default token, but permissions must be set
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: Automated release for version ${{ github.ref_name }}
          draft: false
          prerelease: false
